const express = require("express");
const routes = express();

const User = require("./v1/user.routes");
const Login = require("./v1/login.routes");
const ItemGroup = require("./v1/item_group.routes");
const Item = require("./v1/items.routes");
const Product = require("./v1/product.routes");
const Module = require("./v1/module.routes");
const Permission = require("./v1/permission.routes");
const Item_Product = require("./v1/item_product.routes");
const Company = require("./v1/company.routes");
const Equipmenttype = require("./v1/equipmentType.routes");
const unitOfMeasuremet = require("./v1/unitOfMeasuremet.routes");
const remision = require("./v1/remision.routes");
const clients = require("./v1/client.routes");
const elevatorType = require("./v1/elevatorType.routes");
const typeDriveSystem = require("./v1/typeDriveSystem.routes");
const proyect = require("./v1/proyect.routes");
const product_proyect = require("./v1/product_proyect.routes");
const item_proyect = require("./v1/item_proyect.routes");

routes.use(User);
routes.use(Login);
routes.use(ItemGroup);
routes.use(Item);
routes.use(Product);
routes.use(Module);
routes.use(Permission);
routes.use(Item_Product);
routes.use(Company);
routes.use(Equipmenttype);
routes.use(unitOfMeasuremet);
routes.use(remision);
routes.use(clients);
routes.use(elevatorType);
routes.use(typeDriveSystem);
routes.use(proyect);
routes.use(product_proyect);
routes.use(item_proyect);

module.exports = routes;
